CREATE TABLE tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    citizen_id BIGINT NOT NULL REFERENCES users(id),
    office_id BIGINT NOT NULL REFERENCES offices(id),
    service_id BIGINT NOT NULL REFERENCES services(id),
    counter_id BIGINT REFERENCES counters(id),
    token_number INTEGER NOT NULL,
    queue_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL,
    checked_in_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT uq_token_service_day_number UNIQUE (service_id, queue_date, token_number)
);

CREATE TABLE queue_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    token_id BIGINT NOT NULL REFERENCES tokens(id),
    previous_status VARCHAR(30),
    new_status VARCHAR(30) NOT NULL,
    performed_by BIGINT REFERENCES users(id),
    counter_id BIGINT REFERENCES counters(id),
    note VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
);

CREATE INDEX idx_tokens_citizen_office_status ON tokens(citizen_id, office_id, status);
CREATE INDEX idx_tokens_service_date_status ON tokens(service_id, queue_date, status);
CREATE INDEX idx_queue_history_token_id ON queue_history(token_id);
