CREATE TABLE counter_status_history (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, counter_id BIGINT NOT NULL REFERENCES counters(id), status VARCHAR(20) NOT NULL, occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_counter_status_history_counter_time ON counter_status_history(counter_id, occurred_at);
